# global_config.yaml - Global settings for all switches
base_mac: "52:54:00"  # <- Add quotes here
bios_file: /usr/share/ovmf/OVMF.fd
cdrom_path: /iso2/nxos/config
default_disk_size: 32G
# default_image: nexus9300v64.10.3.8.M.qcow2
default_image: nexus9300v64.10.6.2.F.qcow2
default_interface_type: e1000
default_ram: 16384
default_vcpus: 4
external_storage_enabled: true
image_path: /iso1/nxos/qcow2
